config/routes.rb
Rails.application.routes.draw do
  # get 'registrations/edit'
  get 'messages/index'
  get 'messages/create'
  get 'messages/new'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }, :controllers => { :registrations => "registrations" }
  root to: 'dashboard#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # end
  devise_scope :user do
    get 'users/:id', to: 'users#show', as: 'user'
  end
  get 'chat_rooms/show'
  get 'dashboard/index'
  resources :chats, except: [:edit, :update]
  resources :messages, only: [:create]
  # resources :registrations
  resources :chat_rooms do 
    resources :msgs
  end
  resources :posts
  post "/chat_rooms/:id/send_message", to: "chat_rooms#send_message", as: :send_message
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :messages
    has_and_belongs_to_many :users
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :msgs, dependent: :destroy

  def other_user(current_user)
    users.where.not(id: current_user.id).first
  end

  def other_users(current_user_id)
    if user_one_id != user_two_id
      User.where(id: [user_one_id, user_two_id]).where.not(id: current_user_id)
    else
      User.where(id: current_user_id)
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :post
    mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/msg.rb
class Msg < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images
    mount_uploader :video, VideoUploader
    has_many :chat_room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :confirmable
  
  enum acc_type: [:influncer, :businessman, :admin]
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :acc_type, presence: true
  mount_uploader :profile_image, ImageUploader
  has_and_belongs_to_many :chats
  has_many :messages, through: :chats
  has_many :posts
  has_many :msgs
  has_and_belongs_to_many :chat_rooms
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def new
      @image = Image.new
    end
  
    def create
      @image = Image.new(image_params)
      if @image.save
        redirect_to @image, notice: 'Image was successfully created.'
      else
        render :new
      end
    end
  
    def show
      @image = Image.find(params[:id])
    end
  
    def edit
      @image = Image.find(params[:id])
    end
  
    def update
      @image = Image.find(params[:id])
      if @image.update(image_params)
        redirect_to @image, notice: 'Image was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @image = Image.find(params[:id])
      @image.destroy
      redirect_to images_url, notice: 'Image was successfully destroyed.'
    end
  
    private
      def image_params
        params.require(:image).permit(:image, :post_id)
      end
end
  

app/controllers/msgs_controller.rb
class MsgsController < ApplicationController

  def index
  end

  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @msg = @chat_room.msgs.new(msg_params)
    @msg.save
    ChatRoomChannel.broadcast_to(@chat_room, { msg: render(partial: 'msgs/msg', locals: { msg: @msg }), sender_id: current_user.id, msg_id: @msg.id }) and return
  end

  def new
  end

  private

  def msg_params
    params.require(:msg).permit(:user_id, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  # before_action :process_images, only: [:create, :update]
  def index
    @posts = Post.all.order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      params[:image].each do |image|
        @post.images.create(image: image, post_id: @post.id)
      end
      redirect_to post_path(@post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
     redirect_to posts_path, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.permit(:title, :body, :video, :user_id, images_attributes: [:id, :image])
  end

  def set_post
    @post = Post.find(params[:id])
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
  end
    
  def edit
    @user = current_user
    redirect_to action: 'show', id: @user.id
    if @user.update_without_password(user_params)
      @user.profile_image = params[:user][:profile_image]
      @user.save
      redirect_to root_path, notice: 'Your profile was successfully updated.'
    else
      render :edit
    end
  end
    private 

    def user_params
        params.require(:user).permit(:email,:first_name, :last_name, :phone, :acc_type, :password, :password_confirmation, :current_password, :name, :profile_image)
    end

    def set_user
      @user = User.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top " id="mainNav">
  <div class="container-fluid">
    <%= link_to 'Public Relation Advisor', dashboard_index_path, class:"navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <% if !user_signed_in? %>
          <ul class="navbar-nav ms-auto my-2 my-lg-0">
              <li class="nav-item"><%= link_to "About", dashboard_index_path+"#about", class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Services", dashboard_index_path+"#services", class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Portfolio", dashboard_index_path+"#portfolio", class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Contact", dashboard_index_path+"#contact", class: "nav-link" %></li>
          </ul>
        <% end %>
      </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse auth pad" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       

        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Home", dashboard_index_path,  class: "nav-link text active" %>
        </li>
        <li class="nav-item">
            <%= link_to "Dashboard", posts_path,  class: "nav-link text active" %>
        </li>

        <li class="nav-item">
            <%= link_to "Profile", user_path(current_user.id),  class: "nav-link text active" %>
        </li>

        <li class="nav-item">
            <%= link_to "New Post", new_post_path,  class: "nav-link text active" %>
        </li>

        <li class="nav-item">
            <%= link_to "Chat", chat_rooms_path,  class: "nav-link text active" %>
        </li>

        <li class="navbar-user nav-item">
          <% if current_user.profile_image.present? %>
            <%= image_tag current_user.profile_image.url(:thumb), class: 'navbar-user-img' %>
          <% end %>
        </li>

          <li class="nav-item pad">
            <%= link_to "Sign Out", destroy_user_session_path ,  class: "nav-link btn btn-outline-success" %>
          </li>

        <% else %>
          <li class="nav-item pad">
            <%= link_to 'Log In', new_user_session_path, class:'nav-link btn btn-outline-success'%>
          </li>
          <li class="nav-item pad">
            <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link btn btn-outline-success'%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<style>
.navbar-user {
  display: inline-block;
  vertical-align: middle;
  margin-right: 10px;
}

.navbar-user-img {
  border-radius: 50%;
  width: 45px;
  height: 45px;
  object-fit: cover;
}
</style>

app/views/dashboard/index.html.erb
<%= javascript_include_tag "script" %>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <!-- Masthead-->
        <header class="masthead">
        <% if flash[:error] %>
            <p class = "error-clr"><%= flash[:error] %></p>
        <% end %>
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Your Favorite Place for Public Relations</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">Public Relation Advisor can help you make perfect marketing deals using our top tier service platform! Signup and start today!</p>
                        <a class="btn btn-primary btn-xl" href="#about">Find Out More About Us</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        <h2 class="text-white mb-4">Built Public Relations With Us</h2>
                        <p class="text-white-50">
                            Grayscale is a free Bootstrap theme created by Start Bootstrap. It can be yours right now, simply download the template on
                            The theme is open source, and you can use it for any purpose, personal or commercial.
                        </p>
                        <a class="btn btn-light btn-xl" href="#services">Get Started!</a>
                    </div>
                </div>
                <%= link_to image_tag("ipad.png", class:"img-fluid") %>
            </div>
        </section>
        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container px-4 px-lg-5">
                <h2 class="text-center mt-0">At Your Service</h2>
                <hr class="divider" />
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">Famous Influencers</h3>
                            <p class="text-muted mb-0">We have gathered the best influencers on our platform.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">Keep Track</h3>
                            <p class="text-muted mb-0">Keep track of all of your marketing projects.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">Ready to Roll</h3>
                            <p class="text-muted mb-0">Our platform always have range of people, you can deal with.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">Made with Love</h3>
                            <p class="text-muted mb-0">Public Relations Advisor is made with love to provide best services.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Portfolio-->
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="assets/images/portfolio/fullsize/1.jpg" title="Project Name">
                            <%= link_to image_tag("portfolio/fullsize/1.jpg", class:"img-fluid") %>

                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="assets/images/portfolio/fullsize/2.jpg" title="Project Name">
                            <%= link_to image_tag("portfolio/fullsize/2.jpg", class:"img-fluid") %>
                        
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="assets/images/portfolio/fullsize/3.jpg" title="Project Name">
                            <%= link_to image_tag("portfolio/fullsize/3.jpg", class:"img-fluid") %>
                        
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="assets/images/portfolio/fullsize/4.jpg" title="Project Name">
                            <%= link_to image_tag("portfolio/fullsize/4.jpg", class:"img-fluid") %>
                         
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="assets/images/portfolio/fullsize/5.jpg" title="Project Name">
                            <%= link_to image_tag("portfolio/fullsize/5.jpg", class:"img-fluid") %>
                        
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="assets/images/portfolio/fullsize/6.jpg" title="Project Name">
                            <%= link_to image_tag("portfolio/fullsize/6.jpg", class:"img-fluid") %>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Call to action-->
        <section class="page-section bg-dark text-white">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mb-4">Create account and unleash the power of Public Relations</h2>
              <%= link_to 'Sign Up', new_user_registration_path,  class: "btn btn-light btn-xl" %>
            </div>
        </section>
         <!-- Clients-->
        <div class="py-5">
        <div class="container">
          <div class="row align-items-center">
            <% [["microsoft", "Microsoft Logo", "https://www.microsoft.com/en-pk"], ["google", "Google Logo", "https://www.google.com/"], ["facebook", "Facebook Logo", "https://www.facebook.com/"], ["ibm", "IBM Logo", "https://www.ibm.com/us-en/"]].each do |logo| %>
              <div class="col-md-3 col-sm-6 my-3">
                <%= link_to logo[2], class: "img-brand d-block mx-auto" do %>
                  <%= image_tag "logos/#{logo[0]}.svg", alt: logo[2], class: "img-fluid", aria: { label: logo[1] } %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
         <!-- Contact-->
        <section class="contact-section bg-black" id="contact">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Address</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">Johar Town, Lahore</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50"><a href="#!">PRAdvisor@gmail.com</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Phone</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">+92 (309) 7946938</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social d-flex justify-content-center">
                    <a class="mx-2" href="https://twitter.com/?lang=en"><i class="fab fa-twitter"></i></a>
                    <a class="mx-2" href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
                    <a class="mx-2" href="https://github.com/"><i class="fab fa-github"></i></a>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Your Website 2022</div></footer>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

app/views/msgs/_msg.html.erb
<% if msg.user_id == current_user.id %>
  <div class="message-right" id="msg-<%=msg.id%>">
<% else %>
  <div class="message-left" id="msg-<%=msg.id%>">
<% end %>
  <h1><%= msg.user.first_name %></h1>
  <p><%= msg.body %></p>
</div>

app/views/msgs/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/msgs/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/msgs/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>