config/routes.rb
Rails.application.routes.draw do
  # get 'registrations/edit'
  get 'messages/index'
  get 'messages/create'
  get 'messages/new'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }, :controllers => { :registrations => "registrations" }
  root to: 'dashboard#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # end
  devise_scope :user do
    get 'users/:id', to: 'users#show', as: 'user'
  end
  get 'chat_rooms/show'
  get 'dashboard/index'
  resources :chats, except: [:edit, :update]
  resources :messages, only: [:create]
  # resources :registrations
  resources :chat_rooms do 
    resources :msgs
  end
  resources :posts
  post "/chat_rooms/:id/send_message", to: "chat_rooms#send_message", as: :send_message
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :messages
    has_and_belongs_to_many :users
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :msgs, dependent: :destroy

  def other_user(current_user)
    users.where.not(id: current_user.id).first
  end

  def other_users(current_user_id)
    if user_one_id != user_two_id
      User.where(id: [user_one_id, user_two_id]).where.not(id: current_user_id)
    else
      User.where(id: current_user_id)
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :post
    mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/msg.rb
class Msg < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images
    mount_uploader :video, VideoUploader
    has_many :chat_room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :confirmable
  
  enum acc_type: [:influncer, :businessman, :admin]
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :acc_type, presence: true
  mount_uploader :profile_image, ImageUploader
  has_and_belongs_to_many :chats
  has_many :messages, through: :chats
  has_many :posts
  has_many :msgs
  has_and_belongs_to_many :chat_rooms
  
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
    @chat_rooms = ChatRoom.where.not(user_one_id: nil, user_two_id: nil).where("user_one_id = ? OR user_two_id = ?", current_user.id, current_user.id)
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    @messages = @chat_room.msgs
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    chats = ChatRoom.all
    @chat_room = chats.where(user_one_id: current_user.id, user_two_id: params[:user_two_id]).or(chats.where(user_one_id: params[:user_two_id], user_two_id: current_user.id)).first
    redirect_to @chat_room and return if @chat_room
    @chat_room = ChatRoom.new(chat_room_params)
    @chat_room.user_one_id = current_user.id
    @chat_room.user_two_id = params[:user_two_id]
    if @chat_room.save
      redirect_to @chat_room
    else
      render :new
    end
  end

  def send_message
    @chat_room = ChatRoom.find(params[:id])
    message = Msg.create(chat_room_id: params[:id], body: params[:message])
    ActionCable.server.broadcast("chat_room_#{params[:id]}", message: message.body)
    head :no_content
  end

  private
  
  def chat_room_params
    # params.require(:chat_room).permit(:user_two_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def new
      @image = Image.new
    end
  
    def create
      @image = Image.new(image_params)
      if @image.save
        redirect_to @image, notice: 'Image was successfully created.'
      else
        render :new
      end
    end
  
    def show
      @image = Image.find(params[:id])
    end
  
    def edit
      @image = Image.find(params[:id])
    end
  
    def update
      @image = Image.find(params[:id])
      if @image.update(image_params)
        redirect_to @image, notice: 'Image was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @image = Image.find(params[:id])
      @image.destroy
      redirect_to images_url, notice: 'Image was successfully destroyed.'
    end
  
    private
      def image_params
        params.require(:image).permit(:image, :post_id)
      end
end
  

app/controllers/msgs_controller.rb
class MsgsController < ApplicationController

  def index
  end

  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @msg = @chat_room.msgs.new(msg_params)
    @msg.save
    ChatRoomChannel.broadcast_to(@chat_room, { msg: render(partial: 'msgs/msg', locals: { msg: @msg }), sender_id: current_user.id, msg_id: @msg.id }) and return
  end

  def new
  end

  private

  def msg_params
    params.require(:msg).permit(:user_id, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  # before_action :process_images, only: [:create, :update]
  def index
    @posts = Post.all.order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      params[:image].each do |image|
        @post.images.create(image: image, post_id: @post.id)
      end
      redirect_to post_path(@post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
     redirect_to posts_path, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.permit(:title, :body, :video, :user_id, images_attributes: [:id, :image])
  end

  def set_post
    @post = Post.find(params[:id])
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
  end
    
  def edit
    @user = current_user
    redirect_to action: 'show', id: @user.id
    if @user.update_without_password(user_params)
      @user.profile_image = params[:user][:profile_image]
      @user.save
      redirect_to root_path, notice: 'Your profile was successfully updated.'
    else
      render :edit
    end
  end
    private 

    def user_params
        params.require(:user).permit(:email,:first_name, :last_name, :phone, :acc_type, :password, :password_confirmation, :current_password, :name, :profile_image)
    end

    def set_user
      @user = User.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/index.html.erb
<!-- app/views/chats/index.html.erb -->
<h1>My Chats</h1>

<div class = "container" >
<%= link_to 'New Chat', new_chat_room_path, class: 'btn btn-primary' %>

<ul id="chat_rooms">
  <% @chat_rooms.each do |chat_room| %>
    <% dp = chat_room.other_users(current_user.id).first.profile_image.url %>
    <li class="chat-room">
      <% if dp%>
      <h3><%= link_to image_tag(chat_room.other_users(current_user.id).first.profile_image.url(:thumb)) + "  " + chat_room.other_users(current_user.id).first.first_name , chat_room_path(chat_room) %></h3>
      <% else%>
      <h3><%= link_to chat_room.other_users(current_user.id).first.first_name , chat_room_path(chat_room) %></h3>
      <% end %>
    </li>
  <% end %>
</ul>
</div>

app/views/chat_rooms/new.html.erb
<!-- app/views/chats/new.html.erb -->
<h1 class="text-center mb-5">New Chat</h1>

<div class="row">
  <% users = User.all %>
  <% users.each do |user| %>
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">
            <% if user.profile_image.url %>
              <%= image_tag(user.profile_image.url(:thumb))%>
            <% end %>
            <%= user.first_name %></h5>
          <%= link_to "Start Chat", chat_rooms_path(user_two_id: user.id), method: :post, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/chat_rooms/show.html.erb
<!-- app/views/chat_rooms/show.html.erb -->

<div id="msgs" class= "c">
  <%= render @chat_room.msgs %>
</div>
<div id="msg-form-container">
<%= form_for [@chat_room, Msg.new], remote: true do |form| %>
  <%= form.text_field :body, class: "form-control" %>
  <%= form.submit 'Send', data: {disable_with: false}, class: "send-right" %>
  <%= form.hidden_field :user_id, value: current_user.id %>
<% end %>
</div>

<%= javascript_tag do %>
  App.chat_room = App.cable.subscriptions.create({
    channel: 'ChatRoomChannel',
    id: '<%= @chat_room.id %>'
    }, {
    connected: function() {console.log('connected to chat room')},
    disconnected: function() {console.log('disconnected from chat room')},
    received: function(data) {
      console.log(data)
      document.getElementById('msgs').innerHTML += data.msg;
      document.getElementById(`msg-${data.msg_id}`).classList = data.msg_class
    }
  });
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post-container">
    <div class="post">
      <div class="user-avatar">
        <%= link_to(image_tag(post.user.profile_image.url(:thumb), alt: "User Avatar") + "  " + post.user.first_name + " " + post.user.last_name, post.user, class: "no-link-style") %>
      </div>
      <div class="post-images">
        <% if post.images %>
            <% post.images.each do |image| %>
              <%= image_tag image.image_url, class: "post-image" %>
            <% end %>
        <% end %>
      </div>
      <h2 class="post-title"><%= post.title %></h2>
      <p class="post-body"><%= post.body %></p>
      <% if @chat_room.blank? %>
        <% @chat_room = ChatRoom.create(user_one_id: post.user.id) %>
      <% end %>
      </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="container show-margin">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= form_with url: posts_path, local: true do |form| %>
        <div class="form-group">
          <h3><%= form.label :title %></h3>
          <%= form.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :body %>
          <%= form.text_area :body, class: 'form-control', rows: "5" %>
        </div>
        <div class="form-group">
            <%= form.label :image %>
            <%= form.file_field :image, multiple: true, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= form.label :video %>
            <%= form.file_field :video, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.hidden_field :user_id, value: current_user.id %>
          <%= form.submit "Create Post", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<div class="media-container">
  <% if @post.images.present? %>
    <% @post.images.each do |image| %>
      <%= image_tag image.image_url, class: "post-image" %>
    <% end %>
  <% end %>
  <% if @post.video.present? %>
    <%= video_tag @post.video_url, width: "500", height: "500", type: "video/mp4", controls: true, autoplay: true %>
  <% end %>
</div>
<p><%= @post.body %></p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/_user_show.html.erb
<div class="user-avatar">
    <% if user.profile_image.url %>
        <%= image_tag user.profile_image.url, alt: "User Avatar" %>    
    <% end %>
</div>
<div class="user-details">
    <h2><%= user.first_name %> <%= user.last_name %></h2>
    <p><strong>Email:</strong> <%= user.email %></p>
    <p><strong>Phone:</strong> <%= user.phone %></p>
    <p><strong>Account Type:</strong> <%= user.acc_type %></p>
</div>

app/views/users/show.html.erb
<div class="container show-margin user-info">
  <div class="row">
    <div class="col-md-4">
      <%= render partial: 'user_show', locals: { user: @user }%>
      <% if @user.id == current_user.id %>
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary edit_margin" %>
      <% end %>
      <%= link_to "New Chat", chat_rooms_path(user_two_id: @user.id), method: :post, class: "btn btn-success edit_margin" %>

    </div>
    <div class="row-md-2">
      <h2>Posts by <%= @user.first_name %></h2>
      <% @user.posts.each do |post| %>   
         <div class="post">
            <div class="user-avatar">
              <%= link_to(image_tag(post.user.profile_image.url(:thumb), alt: "User Avatar") + "  " + post.user.first_name + " " + post.user.last_name, post.user, class: "no-link-style") %>
            </div>
            <div class="post-images">
                <% if post.images %>
                    <%= image_tag post.images.first.image_url, class: "post-image" %>
                <% end %>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= post.title %></h5>
                <p class="card-text"><%= truncate(post.body, length: 150) %></p>
                <%= link_to "Read more", post_path(post), class: "btn btn-primary" %>
            </div>
      </div>
      <% end %>
    </div>
  </div>
</div>